name: Gerry Morgan
favicon: null
layout_spectrum: 0.9393215370364487
typography_spectrum: 0.1352843325585127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03535589878447354
  lightness: 0.07259693020023406
  saturation: 0.37493002065457404
  rhythmicContrast: 0.001120253000408411
purpose: []
